In [ ]:
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
c=np.linspace(5,10,5)
c

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [ ]:
o=np.ones((3,3))
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
e=np.eye(2,3)
e

array([[1., 0., 0.],
       [0., 1., 0.]])

In [ ]:
d=np.diag([1,2,3,4])
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
print(a)
print(a[9])
print(a[-1])

[0 1 2 3 4 5 6 7 8 9]
9
9


In [ ]:
a=np.random.randint(0,20,15)
print(a)

[16 16  6 14 19 12 16 11  6 11 11  4  3  1 16]


In [ ]:
mask=

In [ ]:
a=np.array([1,2,5,4])
b=np.array([6,2,9,4])
print(a==b)

[False  True False  True]


In [ ]:
print(a>b)

[False False False False]


In [ ]:
print(a<b)

[ True False  True False]


In [ ]:
print(np.array_equal(a,b))

False


In [ ]:
c=np.array([1,2,3,4,5])
print(np.array_equal(a,c))

False


Logical Operations

In [ ]:
a=np.array([1,0,0,1],dtype=bool)
b=np.array([0,1,0,1],dtype=bool)
print(np.logical_or(a,b))

[ True  True False  True]


In [ ]:
print(np.logical_and(a,b))

[False False False  True]


In [ ]:
print(np.logical_not(a,b))

[False  True  True False]


In [ ]:
a=np.arange(5)+1
print(np.sin(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [ ]:
print(np.log(a))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
print(np.exp(a))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


Shape  mismatch

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,10])
print(a+b)

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,10,2,4])
print(a+b)

[ 6 12  5  8]


In [ ]:
x=np.array([1,2,3,4])
np.sum(x)

10

In [ ]:
y=np.array([[1,2],[3,4]])
print(y)
print("*"*100)
print(y.T)

[[1 2]
 [3 4]]
****************************************************************************************************
[[1 3]
 [2 4]]


In [ ]:
print(y.sum(axis=0))

[4 6]


In [ ]:
print(y.sum(axis=1))

[3 7]


In [ ]:
print(y.max())

4


In [ ]:
#index of min
print(y.argmin())

0


In [ ]:
#index of max
print(y.argmax())

3


Logical Reductions

In [ ]:
print(np.all([True,False,False]))

False


In [ ]:
print(np.any([True,False,False]))

True


In [ ]:
a=np.zeros((50,50))
a
print(np.any(a!=0))

False


Statistics

In [ ]:
x=np.arange(1,10)
print(np.mean(x))

5.0


In [ ]:
print(np.median(x))

5.0


In [ ]:
y=np.array([[1,2,3],[4,5,6]])
print(np.mean(y,axis=0))
print(np.mean(y,axis=1))

[2.5 3.5 4.5]
[2. 5.]


In [ ]:
print(np.std(x))

2.581988897471611


In [ ]:
#create one dimensional array from list
l=[12.3,13.32,100,30.35]
import numpy as np
array_from_list = np.array(l)
print(array_from_list)


[ 12.3   13.32 100.    30.35]


craete 3x3 matrix with elements 2 to 10

In [ ]:
a=np.arange(2,11)
m=a.reshape(3,3)
m

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

write a numpy program to sort an along the first axis, last axis of an array

In [ ]:
arr=np.array([[4,6],[2,1]])
print(arr)
print(np.sort(arr,axis=0))
print(np.sort(arr,axis=1))

[[4 6]
 [2 1]]
[[2 1]
 [4 6]]
[[4 6]
 [1 2]]


Write a numpy progran to create a contiguous flattened array

In [ ]:
a=np.array([[10,20,30],[20,40,50]])
print(np.ravel(a))

[10 20 30 20 40 50]


Write a numpy program to display all the dates of march 2017

In [ ]:
print("March, 2017")
print(np.arange('2017-03', '2017-04', dtype='datetime64[D]'))

March, 2017
['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']
